In [1]:
import pandas as pd
df=pd.read_csv("class_ipl_22-26_dataset.csv")
df.head()

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,26-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,131,5,...,6,UT Yadav,M Nayyar,AK Chaudhary,Nitin Menon,VK Sharma,Chirra Ravikanthreddy,20,"RD Gaikwad, DP Conway, RV Uthappa, AT Rayudu, ...","AM Rahane, VR Iyer, N Rana, SS Iyer, SW Billin..."
1,27-03-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Mumbai Indians,Delhi Capitals,Delhi Capitals,field,177,5,...,4,Kuldeep Yadav,Prakash Bhatt,RJ Tucker,HAS Khalid,J Madanagopal,N Pandit,20,"RG Sharma, Ishan Kishan, Anmolpreet Singh, Til...","PP Shaw, TL Seifert, Mandeep Singh, RR Pant, L..."
2,27-03-2022,2022,Mumbai,"Dr DY Patil Sports Academy, Mumbai",Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,205,2,...,5,OF Smith,M Nayyar,Nitin Menon,YC Barde,AK Chaudhary,R Pandit,20,"F du Plessis, Anuj Rawat, V Kohli, KD Karthik,...","MA Agarwal, S Dhawan, PBB Rajapaksa, LS Living..."
3,28-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Lucknow Super Giants,Gujarat Titans,Gujarat Titans,field,158,6,...,5,Mohammed Shami,DS Manohar,PG Pathak,VK Sharma,RJ Tucker,GR Sadashiv Iyer,20,"KL Rahul, Q de Kock, E Lewis, MK Pandey, DJ Ho...","Shubman Gill, MS Wade, V Shankar, HH Pandya, D..."
4,29-03-2022,2022,Pune,"Maharashtra Cricket Association Stadium, Pune",Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,210,6,...,0,SV Samson,Shakti Singh,BNJ Oxenford,UV Gandhe,KN Ananthapadmanabhan,MV Saidharshan Kumar,20,"JC Buttler, YBK Jaiswal, SV Samson, D Padikkal...","KS Williamson, Abhishek Sharma, RA Tripathi, N..."

In [2]:
x=df[['team1_runs']]
x.head()

   team1_runs
0         131
1         177
2         205
3         158
4         210

In [3]:
mean=x['team1_runs'].mean()
minimum=x['team1_runs'].min()
maximum=x['team1_runs'].max()
print("mean:",mean)
print("minimum:",minimum)
print("maximum:",maximum)

mean: 185.0708446866485
minimum: 25
maximum: 287

In [4]:
x_mean=x.copy()
x_mean['team1_runs']=(x_mean['team1_runs']-mean)/(maximum-minimum)
x_mean.head()

   team1_runs
0   -0.206377
1   -0.030805
2    0.076065
3   -0.103324
4    0.095149

In [8]:
comparison=pd.DataFrame({
    'original':x['team1_runs'],
    'mean_scaled':x_mean['team1_runs']
})
#pd.set_option('display.max_rows', None)
comparison.head()

   original  mean_scaled
0       131    -0.206377
1       177    -0.030805
2       205     0.076065
3       158    -0.103324
4       210     0.095149

In [9]:
print("original data: ",x.describe().round(2))
print("mean normalized: ",x_mean.describe().round(2))

original data:         team1_runs
count      367.00
mean       185.07
std         36.52
min         25.00
25%        161.50
50%        187.00
75%        209.00
max        287.00
mean normalized:         team1_runs
count      367.00
mean        -0.00
std          0.14
min         -0.61
25%         -0.09
50%          0.01
75%          0.09
max          0.39