In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
df=pd.read_csv("IPLPlayerStat.csv")
df.head()

,Unnamed: 0,player,runs,boundaries,balls_faced,wickets,balls_bowled,runs_conceded,matches,batting_avg,batting_strike_rate,boundaries_percent,bowling_economy,bowling_avg,bowling_strike_rate,catches,stumpings
0,0,A Ashish Reddy,280,31,196,18.0,270.0,400.0,28,10.00,142.86,15.82,8.89,22.22,15.00,8.0,0.0
1,1,A Badoni,161,18,139,2.0,12.0,12.0,11,14.64,115.83,12.95,6.00,6.00,6.00,8.0,0.0
2,2,A Chandila,4,0,7,11.0,234.0,245.0,12,0.33,57.14,0.00,6.28,22.27,21.27,2.0,0.0
3,3,A Chopra,53,7,75,0.0,0.0,0.0,6,8.83,70.67,9.33,0.00,0.00,0.00,2.0,0.0
4,4,A Choudhary,25,2,20,5.0,108.0,144.0,5,5.00,125.00,10.00,8.00,28.80,21.60,0.0,0.0

In [6]:
def player_form(avg):
    if avg <= 10:
        return"poor"
    elif avg <= 15:
        return"average"
    elif avg <= 20:
        return "good"
    elif avg <= 25:
        return "excellent"
    else:
        return "outstanding"
df["player_form"]=df["batting_avg"].apply(player_form)
df[["player","batting_avg","player_form"]].head()

           player  batting_avg player_form
0  A Ashish Reddy        10.00        poor
1        A Badoni        14.64     average
2      A Chandila         0.33        poor
3        A Chopra         8.83        poor
4     A Choudhary         5.00        poor

In [7]:
df["player_form"].unique()

<StringArray>
['poor', 'average', 'excellent', 'good', 'outstanding']
Length: 5, dtype: str

In [8]:
encoder=OrdinalEncoder(categories=[["poor","average","good","excellent","outstanding"]])
df["player_form_encoded"]=encoder.fit_transform(df[["player_form"]]).astype(int)
df[["player_form","player_form_encoded"]].tail(30)

     player_form  player_form_encoded
575         poor                    0
576  outstanding                    4
577         poor                    0
578         poor                    0
579         poor                    0
580      average                    1
581         poor                    0
582         poor                    0
583         poor                    0
584         good                    2
585         poor                    0
586         poor                    0
587    excellent                    3
588         poor                    0
589         poor                    0
590         poor                    0
591         poor                    0
592      average                    1
593         poor                    0
594         good                    2
595         poor                    0
596    excellent                    3
597    excellent                    3
598         poor                    0
599         good                    2
600         poor                    0
601      average                    1
602         poor                    0
603    excellent                    3
604         poor                    0

In [9]:
df[["player","batting_avg","player_form","player_form_encoded"]].head(20)

            player  batting_avg  player_form  player_form_encoded
0   A Ashish Reddy        10.00         poor                    0
1         A Badoni        14.64      average                    1
2       A Chandila         0.33         poor                    0
3         A Chopra         8.83         poor                    0
4      A Choudhary         5.00         poor                    0
5      A Dananjaya         4.00         poor                    0
6       A Flintoff        20.67    excellent                    3
7         A Kumble         0.83         poor                    0
8        A Manohar        15.43         good                    2
9         A Mishra         2.35         poor                    0
10        A Mithun         2.12         poor                    0
11        A Mukund         9.50         poor                    0
12         A Nehra         0.47         poor                    0
13        A Nortje         0.27         poor                    0
14         A Singh         0.09         poor                    0
15       A Symonds        27.06  outstanding                    4
16         A Tomar         4.00         poor                    0
17        A Uniyal         2.00         poor                    0
18         A Zampa         0.36         poor                    0
19     AA Bilakhia         9.86         poor                    0